services:
  otlp-collector:
    image: otel/opentelemetry-collector
    restart: always
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4318:4318"
      - "4317:4317"
    volumes:
      - "./collector-config.yaml:/etc/otelcol/config.yaml"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"