services:
  otlp-collector:
    image: otel/opentelemetry-collector
    restart: always
    ports:
      - "8889:8889"
      - "4318:4318"
      - "4317:4317"
    volumes:
      - "./collector-config.yaml:/etc/otelcol/config.yaml"

  prometheus:
  # https://github.com/grafana/grafana/issues/80185
    image: prom/prometheus:v2.49.1
    restart: always
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"

  grafana:
    image: grafana/grafana-enterprise
    restart: always
    ports: 
      - "3333:3000"